/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace AfterShipTracking
{
    /// <summary>
    /// All available additional fields
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum AdditionalFields
    {
        [EnumMember(Value = "tracking_account_number")]
        TrackingAccountNumber,
        [EnumMember(Value = "destination_postal_code")]
        DestinationPostalCode,
        [EnumMember(Value = "destination_state")]
        DestinationState,
        [EnumMember(Value = "tracking_key")]
        TrackingKey,
        [EnumMember(Value = "origin_country_region")]
        OriginCountryRegion,
        [EnumMember(Value = "destination_country_region")]
        DestinationCountryRegion,
        [EnumMember(Value = "tracking_ship_date")]
        TrackingShipDate,
    }
}
