/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
using System;
using System.Collections.Generic;
using Newtonsoft.Json;

namespace AfterShipTracking
{
    /// <summary>
    /// 
    /// </summary>
    public class  GetCourierConnectionsResponse
    {
        /// <summary>
        ///  Pagination 
        /// </summary>
        [JsonProperty("pagination")]
        public PaginationGetCourierConnectionsResponse?  Pagination { get; set; }
        /// <summary>
        ///  CourierConnections 
        /// </summary>
        [JsonProperty("courier_connections")]
        public CourierConnection? [] CourierConnections { get; set; }
        /// <summary>
        ///  Page 
        /// </summary>
        [JsonProperty("page")]
        public int?  Page { get; set; }
        /// <summary>
        ///  Limit 
        /// </summary>
        [JsonProperty("limit")]
        public int?  Limit { get; set; }
        /// <summary>
        ///  Count 
        /// </summary>
        [JsonProperty("total")]
        public int?  Count { get; set; }
        public GetCourierConnectionsResponse()
        {
        }
    }
    
    /// <summary>
    /// 
    /// </summary>
    public class  PaginationGetCourierConnectionsResponse
    {
        /// <summary>
        ///  Total The total number of courier connections.
        /// </summary>
        [JsonProperty("total")]
        public int?  Total { get; set; }
        /// <summary>
        ///  NextCursor A string representing the cursor value for the next page of results.
        /// </summary>
        [JsonProperty("next_cursor")]
        public string?  NextCursor { get; set; }
        /// <summary>
        ///  HasNextPage To indicate if next page is available.
        /// </summary>
        [JsonProperty("has_next_page")]
        public bool?  HasNextPage { get; set; }

        public PaginationGetCourierConnectionsResponse()
        {
        }
    }
    /// <summary>
    /// 
    /// </summary>
    public class  GetCourierConnectionsResponseCourierConnectionListData
    {
        /// <summary>
        ///  CourierConnections 
        /// </summary>
        [JsonProperty("courier_connections")]
        public CourierConnection? [] CourierConnections { get; set; }
        /// <summary>
        ///  Pagination 
        /// </summary>
        [JsonProperty("pagination")]
        public PaginationPage?  Pagination { get; set; }

        public GetCourierConnectionsResponseCourierConnectionListData()
        {
        }
    }
}
