/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
using System;
using System.Net.Http;

namespace AfterShipTracking
{
    public class EstimatedDeliveryDateService : BaseResourceService
    {
        IHttpClient HttpClient;

        public EstimatedDeliveryDateService(IHttpClient httpClient)
        {
            this.HttpClient = httpClient;
        }

        public EstimatedDeliveryDateResponse Predict(PredictOptions? options = null)
        {
            string path = $"/tracking/2025-01/estimated-delivery-date/predict";
            Request request = new Request(
                HttpMethod.Post,
                path,
                options
            );

            var response = this.HttpClient.MakeRequest(request);
            return ProcessData<EstimatedDeliveryDateResponse>(response);
        }
        public PredictBatchResponse PredictBatch(PredictBatchOptions? options = null)
        {
            string path = $"/tracking/2025-01/estimated-delivery-date/predict-batch";
            Request request = new Request(
                HttpMethod.Post,
                path,
                options
            );

            var response = this.HttpClient.MakeRequest(request);
            return ProcessData<PredictBatchResponse>(response);
        }
    }
}

