/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
using Newtonsoft.Json;

namespace AfterShipTracking
{
    public class PaginationPage
    {
        /// <summary>
        /// Page index
        /// </summary>
        [JsonProperty("cursor")]
        public string? Cursor { get; set; }

        /// <summary>
        /// Total count
        /// </summary>
        [JsonProperty("total")]
        public int? Total { get; set; }


        /// <summary>
        /// Total count
        /// </summary>
        [JsonProperty("has_next_page")]
        public bool? HasNextPage { get; set; }

        public PaginationPage(string? cursor, int? total, bool hasNextPage = false)
        {
            Cursor = cursor;
            Total = total;
            HasNextPage = hasNextPage;
        }
    }
}

